import Img from "@/components/lazyLoadImage/Img";
import LoadingSpinner from "@/components/loadingSpinner/LoadingSpinner";
import useFetch from "@/hooks/useFetch";
import Style from "@/styles/expre.module.css";
import { TITLE } from "@/utils/api";
import { baseImgUrl } from "@/utils/imgUrl";
import Head from "next/head";
import { Col, Container, Row } from "react-bootstrap";

export default function Home() {
  const { data, loading } = useFetch("/expre");
  console.log(data?.data);
  
  return (
    <>
      <Head>
        <title>EX PRESIDENT SECRETARY:: {TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./shreepur.jpeg" />
      </Head>
      <main>
        {loading ? (
          <LoadingSpinner />
        ) : (
          <>
            {/* Advisor Details */}
            <Container className="mt-4">
              <Row>
                <div className="headerTitle">
                  <h3 className="headerTitleMain"> সভাপতি ও সাধারণ সম্পাদকের তালিকা </h3>
                </div>

                {data?.data?.map((item) => (
                  <Col lg={6} md={6} sm={12} key={item?.id}>
                    <div className={`${Style.cardDesign} d-flex gap-3 justify-content-center justify-items-center align-items-center`} data-aos="fade-up">
                   <div>
                   {item?.image !== null ? (
                        <Img
                          src={baseImgUrl + item?.image}
                          className={Style.cardImg}
                        />
                      ) : (
                        <Img src="./default.png" className={Style.cardImg} />
                      )}
                   </div>

                     <div>
                     <h4 className={Style.name}>{item?.name}</h4>
                      <h5 className={Style.category}>{item?.category==='President'?'সভাপতি':'সাধারণ সম্পাদক'}</h5>
                      <p>{item?.date1}</p>
                     </div>
                    </div>
                  </Col>
                ))}
              </Row>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
