import MemberSkeleton from "@/components/loader/MemberSkeleton";
import NoticeCard from "@/components/noticeCard/NoticeCard";
import useFetch from "@/hooks/useFetch";
import { TITLE } from "@/utils/api";
import Head from "next/head";
import { Container, Row } from "react-bootstrap";

export default function Notice() {
  const { data, loading } = useFetch("/notice");
  return (
    <>
      <Head>
        <title>NOTICE:: {TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./shreepur.jpeg" />
      </Head>
      <main>
        {loading ? (
          <MemberSkeleton />
        ) : (
          <>
            {/* Notice Title */}
            <div className="headerTitle mt-3">
              <h3 className="headerTitleMain">নোটিশ</h3>
            </div>
            {/* Notice Details */}
            <Container className="mt-4">
              <Row className="mb-4">
                {data?.data?.map((item) => (
                  <NoticeCard key={item.serial} item={item} />
                ))}
              </Row>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
