import Head from "next/head";
import useFetch from "@/hooks/useFetch";
import { Container, Row } from "react-bootstrap";
import CardDesign from "@/components/cardDesign/CardDesign";
import { useState } from "react";
import LoadingSpinner from "@/components/loadingSpinner/LoadingSpinner";
import { TITLE } from "@/utils/api";
import Pagination from "@/components/pagination/Pagination";

export default function Home() {
  const [page, setPage] = useState(1);
 

  const { data, loading } = useFetch(`/PaginationMember/Pass?page=${page}`);

  const handleNextPage = () => {
    if(page>=data?.last_page){
      setPage(data?.last_page)
    }
    setPage(page + 1);
  }
  const handlePrevPage = () => {
    if(page <= 0){
      setPage(1)
    }
    setPage(page - 1);
  }

  return (
    <>
      <Head>
        <title>GENERAL:: {TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./shreepur.jpeg" />
      </Head>
      <main>
        {loading ? (
          <LoadingSpinner />
        ) : (
          <>
            <div className="headerTitle mt-3">
              <h3 class="headerTitleMain">প্রায়ত সদস্য</h3>
            </div>
            {/* Advisor Details */}
            <Container className="mt-4">
              <Row>
                {data?.data?.map((item) => (
                  <CardDesign key={item.serial} item={item} />
                ))}
              </Row>

              <div>
                <Pagination page={data?.page} last_page={data?.last_page} handleNextPage={handleNextPage} handlePrevPage={handlePrevPage}></Pagination>
              </div>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
